#! /usr/bin/python
import RPI.GPIO as GPIO
from time import sleep
from firebase import firebase
firebase = firebase.FirebaseApplication('https://xxxfirebaseio.com/')

sensor='x'  # Pin No
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(sensor, GPIO.IN, GPIO.PUD_UP)

def my_callback(channel)
    if (GPIO.input(sensor)):
        print("Toilet is vacant")
        firebase.post('/door', {'state':'Toilet is vacant'}) # Post data to new key state
        firebase.put('door', 'state', 'Toilet is vacant')    # Add data to key state
    else:
        print("Toilet is occupied")
        firebase.post('/door', {'state':'Toilet is occupied'}) # Post data to new key state
        firebase.put('door', 'state', 'Toilet is occupied')    # Add data to key state

GPIO.add_event_detect(sensor, GPIO.BOTH, callback = my_callback, bounctime=500)

while (True):
    sleep(0.5)

    